### ISSUE TITLE
Custom graphql.execution.DataFetcherExceptionHandler

### ISSUE THREAD

**Issue by paullarionov** [graphql-java-kickstart/graphql-spring-boot#179]
Hello Dear Friend,

I would like to make custom `graphql.execution.DataFetcherExceptionHandler` for my application like at https://www.graphql-java.com/documentation/v10/execution/:

```        
DataFetcherExceptionHandler handler = new DataFetcherExceptionHandler() {
    @Override
    public void accept(DataFetcherExceptionHandlerParameters handlerParameters) {
                  // do your custom handling here.  The parameters have all you need
    }
};

ExecutionStrategy executionStrategy = new AsyncExecutionStrategy(handler);
```

Is it possible with graphql-spring-boot?

**Comment by oliemansm** [comment]
@paullarionov You want to customize the error result in the response or do you want to do something else at that point?

Because customizing the response is possible by either adding your own custom graphql error handler, or since 5.3 by using the `@ExceptionHandler` annotation, see: https://github.com/graphql-java-kickstart/graphql-spring-boot/releases/tag/v5.3.

**Comment by paullarionov** [comment]
Hi @aleclerc @oliemansm ,

I suppose executionStrategies from @aleclerc is good for me! Thanks!

**Comment by ankit-joinwal** [comment]
@paullarionov can you give the code snippet how you did it?

**Comment by paullarionov** [comment]
@ankit-joinwal sorry, no snippet available
