### ISSUE TITLE
Voyager missing change introspection feature

### ISSUE THREAD

**Issue by elenigen** [graphql-java-kickstart/graphql-spring-boot#214]
It looks like there's a feature to switch the Root level, for now by default it's displaying all the queries, but if we want to look at the mutations, I don't see any options for that, while it looks like it's available in the original Voyager project.
Any tips?

**Comment by oliemansm** [comment]
From their docs it doesn't look like they provide a configuration option to allow switching root type on the fly. I do see they have a `displayOptions` object that allows you to configure the root type to use amongst other stuff. We could (and probably should) support that, but that will only set it at startup as configured using your Spring properties. So that doesn't give you the option to switch the root type while using Voyager itself. That would be better I'd say, but that would be a question for the [Voyager project](https://github.com/APIs-guru/graphql-voyager).

**Comment by elenigen** [comment]
Actually, I just realized it's possible to do it already:
![image](https://user-images.githubusercontent.com/8632319/55346612-e5d50200-5480-11e9-97c7-65a3c46552bd.png)

... but yes, it would still be nice to be able to choose the startup root type.
