### ISSUE TITLE
Schema stitching?

### ISSUE THREAD

**Issue by SledgeHammer01** [graphql-java-kickstart/graphql-spring-boot#319]
Hi,
I have 2 graphqls files in my resources directory. Seems like only one of them is getting picked up. Do I need to do anything special to support schema merging? I can't find any information on it.

**Comment by oliemansm** [comment]
No they should be picked up automatically. As a matter of fact, we use that in production for several projects. Are you duplicating types though? So do both have a `type Query` defined for example? Because that might cause trouble. In that case you should either define the type in one of the two files, or try to `extend type Query` in one of the files (haven't tried that approach myself though).

**Comment by oliemansm** [comment]
@SledgeHammer01 Is this still causing you trouble or can we close the issue?
