### ISSUE TITLE
Wrong version of Spring in resulting artifact

### ISSUE THREAD

**Issue by dimi-nk** [graphql-java-kickstart/graphql-spring-boot#370]
Looking at the code [here](https://github.com/graphql-java-kickstart/graphql-spring-boot/blob/master/gradle.properties#L43), I can see that in version `6.0.1` the corresponding SPring version is `2.2.5.RELEASE`. However, when looking at the org.maven, the [page](https://search.maven.org/artifact/com.graphql-java-kickstart/graphql-spring-boot-autoconfigure/6.0.1/jar) reports `2.2.1.RELEASE`. Do you know how that is possible?

**Comment by DarkBlade47** [comment]
graphql-spring-boot-starter version 6.0.1 was published to maven repository in december 2019.

What you are looking at here is 3-4 months of development time since then, Code still refers to itself as 6.0.1, they will probably bump the number up to 6.0.2 next time they release.
Meanwhile i have downloaded the code, compiled the jars and using those in my project.

**Comment by dimi-nk** [comment]
@DarkBlade47 yeah makes sense, didn't think about that. I would expect a different version to be shown, e.g. `SNAPSHOP`. Anyway, this doesn't look like an issue then.

**Comment by DarkBlade47** [comment]
I am not very familiar with the versioning system, but i would expect to see the version as SNAPSHOT aswell. Not sure why it's not.
