### ISSUE TITLE
NoSuchBeanDefinitionException: No qualifying bean of type 'graphql.GraphQL' available:

### ISSUE THREAD

**Issue by afuyo** [graphql-java-kickstart/graphql-spring-boot#489]
I run into this error when running graphql-java-generator and graphq-java-kickstart.  
`nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'graphql.GraphQL' available: expected at least 1 bean which qualifies as autowire candidate NoSuchBeanDefinitionException: No qualifying bean of type 'graphql.GraphQL' available:`

Here is the snippet from my pom.xml
``` <properties>
	<graphql-maven-plugin.version>1.11</graphql-maven-plugin.version>
</properties>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.0</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
/---/
	<dependency>
			<groupId>com.graphql-java-kickstart</groupId>
			<artifactId>graphql-spring-boot-starter</artifactId>
			<version>8.0.0</version>
		</dependency>

		<dependency>
			<groupId>com.graphql-java-generator</groupId>
			<artifactId>graphql-java-runtime</artifactId>
			<version>${graphql-maven-plugin.version}</version>
		</dependency>
```
It can be reproduce by adding the graphql-jave-generator dependency. When I remove the spring boot program works again.

**Comment by oliemansm** [comment]
You should raise the issue with the `graphql-java-generator` team then instead of here. I've never heard or used that library before, and we don't have the resources to provide support for integrating with third party libraries. So maybe they can help. Or otherwise raise an issue on Stackoverflow with more detailed information (like stack traces and minimal code to reproduce the issue).
