### ISSUE TITLE
GraphQLTestAutoConfiguration tries to autowire TestRestTemplate regardless of WebEnvironment

### ISSUE THREAD

**Issue by lassemaatta** [graphql-java-kickstart/graphql-spring-boot#544]
**Describe the bug**
When the `GraphQLTestAutoConfiguration` class attempts to initialize the `graphQLTestUtils` bean, a `NoSuchBeanDefinitionException` is thrown because `TestRestTemplate` could not be autowired.

**To Reproduce**
1. Create a simple working Spring application
2. Add tests using `@SpringBootTest` (aka. with `webEnvironment = WebEnvironment.MOCK`) and check that they run
3. Add dependency to `graphql-spring-boot-starter` and `graphql-spring-boot-starter-test`
4. Notice how existing tests now fail to start due to `NoSuchBeanDefinitionException`

**Expected behavior**
Adding the graphql dependencies should not break existing tests.

**Additional context**
A workaround is to explicitly disable graphql for the existing tests, using eg. `@SpringBootTest(properties = "graphql.servlet.enabled=false")`

**Comment by streibeb** [comment]
I have this exact same issue, however your workaround doesn't work for me as I get another error:

`Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'graphQLWebsocketServlet' defined in class path resource [graphql/kickstart/spring/web/boot/GraphQLWebsocketAutoConfiguration.class]: Unsatisfied dependency expressed through method 'graphQLWebsocketServlet' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'graphql.kickstart.execution.subscriptions.GraphQLSubscriptionInvocationInputFactory' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
`

**Comment by lassemaatta** [comment]
@streibeb have you tried also setting `graphql.servlet.websocket` to `false`? That property is used by the `GraphQLWebsocketAutoConfiguration` class.

```java
@SpringBootTest(properties = {
        "graphql.servlet.enabled=false",
        "graphql.servlet.websocket.enabled=false"
})
```

**Comment by streibeb** [comment]
@lassemaatta That worked, thank you!

**Comment by dhasilin** [comment]
+1
Issue might be also be caused by 
`@ConditionalOnProperty(value = "graphql.servlet.enabled", havingValue = "true", matchIfMissing = true)` 

Slightly nicer approach for now is to disable auto config in general configuration file:
 `@EnableAutoConfiguration(exclude = {GraphQLTestAutoConfiguration.class})`

After that you could create local config with GraphQL enabled

**Comment by thanhj** [comment]
You don't need to make `graphql.servlet.enabled=false`.
TestRestTemplate is only auto-configured when @SpringBootTest has been configured with a webEnvironment.
So the simplest way to fix this is adding `webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT` to your @SpringBootTest.

**Comment by debu999** [comment]
with com.graphql-java-kickstart.graphiql-spring-boot-starter:11.0.0 and com.graphql-java-kickstart.graphql-spring-boot-starter-test:11.0.0 we only need to add 
`@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)`
Voila it works as expected. We can have something else done either. Not sure why the above just work without the property change.
