### ISSUE TITLE
Can`t disable GraphQLErrorFromExceptionHandler 

### ISSUE THREAD

**Issue by Thinkenterprise** [graphql-java-kickstart/graphql-spring-boot#611]
If I use ``@ExceptionsHandler`` in my Resolvers I can't disable the use of the ``GraphQLErrorFromExceptionHandler``. But I need to disable the feature!!

I think the problem is in the following class:
 
```
 public class GraphQLErrorHandlerFactory {

  public GraphQLErrorHandler create(ConfigurableApplicationContext applicationContext,
      boolean exceptionHandlersEnabled) {
  
    if (!factories.isEmpty() || exceptionHandlersEnabled) {
      log.debug("Handle GraphQL errors using exception handlers defined in {} custom factories",
          factories.size());
      return new GraphQLErrorFromExceptionHandler(factories);
    }
```
 I think it should be ``if (!factories.isEmpty() && exceptionHandlersEnabled)`` and not ``||`` right?

**Comment by oliemansm** [comment]
@Thinkenterprise Not an `&&` actually, but the check if `factories` is non-empty should be removed here. Otherwise if we'd make it an AND instead of OR check you'd have to add at least one `@ExceptionHandler` yourself to really enable this setting. While the idea is that you don't have to add any `@ExceptionHandler` annotated methods at all if you don't want to and can just set that setting to `true` to get started with this.

Seeing the rest of that piece of code I don't see and can't recall what the added value would be of having that collections check in here in the first place, so I'll remove it.

**Comment by Thinkenterprise** [comment]
@oliemansm Yes you are right. I was to fast :-( The change helps!! Thanks for your fast response
